- id: gofmt
  name: Go Fmt
  entry: golang/gofmt.sh
  language: script
  files: \.go$
  exclude: (^vendor/)|(\.pb\.go$)
- id: goimports
  name: Go Imports
  entry: golang/goimports.sh
  language: script
  files: \.go$
  exclude: (^vendor/)|(\.pb\.go$)
- id: go-vet
  name: Go Vet
  entry: golang/go-vet.sh
  language: script
  files: \.go$
  exclude: (^vendor/)|(\.pb\.go$)
- id: go-mod-tidy
  name: Go Mod Tidy
  entry: golang/go-mod-tidy.sh
  language: script
  files: (\.go$)|(go\.mod)|(go\.sum)
  exclude: ^vendor/
- id: thriftfmt
  name: Thrift Format
  entry: thrift/thriftfmt.sh
  language: script
  files: \.thrift$
- id: prototool
  name: prototool
  entry: protobuf/prototool.sh
  language: script
  files: (\.proto$)|(prototool.yaml)｜(prototool.json)
  pass_filenames: false
- id: golangci-lint
  name: golangci-lint
  entry: golang/golangci-lint.sh
  language: script
  files: \.go$
  exclude: (^vendor/)|(\.pb\.go$)
  pass_filenames: false
